;; Generated by :claw at 2021-06-10T22:00:51.690336+03:00
(asdf:defsystem #:aw-skia-bindings
  :description "Bindings generated by aw-skia"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi :float-features :claw-utils)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))
   (:file "bindings/aarch64-linux-android" :if-feature
    (:and :aarch64 :android))))
