;; Generated by :claw at 2021-05-29T22:56:23.715007+03:00
(asdf:defsystem #:claw-skia-bindings
  :description "Bindings generated by claw-skia"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi :claw-utils)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))
   (:file "bindings/aarch64-linux-android" :if-feature
    (:and :aarch64 :android))))